#!/usr/bin/env bash
# =============================================================================
# scripts/install_service.sh — Install WALL-E as a boot-time systemd service
# =============================================================================
# Run ONCE on the Pi:
#   cd ~/walle && bash scripts/install_service.sh
#
# After this:
#   - WALL-E starts automatically when the Pi boots
#   - No manual "sudo systemctl start walle-hw" needed
#   - Restarts itself if it crashes
#   - Logs visible with: sudo journalctl -u walle-hw -f
# =============================================================================

set -uo pipefail

RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'; CYAN='\033[0;36m'; NC='\033[0m'
log()     { echo -e "${GREEN}[SETUP]${NC} $*"; }
warn()    { echo -e "${YELLOW}[WARN]${NC}  $*"; }
err()     { echo -e "${RED}[ERROR]${NC} $*"; exit 1; }
info()    { echo -e "${CYAN}[INFO]${NC}  $*"; }

# ── Must NOT be run as root ───────────────────────────────────────────────────
[[ $EUID -eq 0 ]] && err "Run as the walle user, NOT root. (sudo is used internally)"

# ── Auto-detect paths ─────────────────────────────────────────────────────────
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
CURRENT_USER="$(whoami)"
VENV_DIR="$PROJECT_DIR/.venv"
PYTHON_BIN="$VENV_DIR/bin/python"
SERVICE_NAME="walle-hw"
SERVICE_DST="/etc/systemd/system/${SERVICE_NAME}.service"

log "=== WALL-E Auto-Boot Service Installer ==="
info "User:        $CURRENT_USER"
info "Project:     $PROJECT_DIR"
info "Python:      $PYTHON_BIN"
info "Service:     $SERVICE_DST"

# ── Validate Python venv ─────────────────────────────────────────────────────
if [[ ! -f "$PYTHON_BIN" ]]; then
    err "Python venv not found at $PYTHON_BIN. Run: python3 -m venv $VENV_DIR && pip install -r requirements.txt"
fi

# ── Validate .env exists ─────────────────────────────────────────────────────
if [[ ! -f "$PROJECT_DIR/.env" ]]; then
    err ".env file not found at $PROJECT_DIR/.env. Copy .env.example and fill in GEMINI_API_KEY."
fi

# ── Detect audio runtime (PipeWire or PulseAudio) ────────────────────────────
PULSE_DIR="/run/user/$(id -u)/pulse"
PIPEWIRE_DIR="/run/user/$(id -u)/pipewire-0"
AUDIO_ENV=""

if [[ -e "$PIPEWIRE_DIR" ]] || systemctl --user is-active pipewire.service &>/dev/null 2>&1; then
    info "Audio: PipeWire detected."
    AUDIO_ENV="Environment=XDG_RUNTIME_DIR=/run/user/$(id -u)"
elif [[ -e "$PULSE_DIR" ]] || systemctl --user is-active pulseaudio.service &>/dev/null 2>&1; then
    info "Audio: PulseAudio detected."
    AUDIO_ENV="Environment=PULSE_RUNTIME_PATH=/run/user/$(id -u)/pulse"
else
    warn "No audio server detected — service will still be installed."
fi

# ── Write the systemd service file ───────────────────────────────────────────
log "Writing ${SERVICE_DST}..."

sudo tee "$SERVICE_DST" > /dev/null << EOF
# /etc/systemd/system/walle-hw.service
# WALL-E AI Hardware Service — Auto-generated by scripts/install_service.sh
# Regenerate with: bash ~/walle/scripts/install_service.sh

[Unit]
Description=WALL-E AI Voice Assistant (Hardware Mode)
Documentation=https://github.com/SahilKumar337/COCO
# Wait for network so Gemini API works on first boot
After=network-online.target
Wants=network-online.target
# Wait for sound subsystem
After=sound.target

[Service]
Type=simple
User=${CURRENT_USER}
Group=${CURRENT_USER}
WorkingDirectory=${PROJECT_DIR}

# Environment from .env file
EnvironmentFile=${PROJECT_DIR}/.env

# Python / stdout settings
Environment=PYTHONUNBUFFERED=1
Environment=PYTHONDONTWRITEBYTECODE=1
Environment=HOME=/home/${CURRENT_USER}

# Audio server access (PipeWire/PulseAudio need XDG_RUNTIME_DIR)
${AUDIO_ENV}

# Entry point: main.py = hardware mode (wake word + mic + speaker)
ExecStart=${PYTHON_BIN} ${PROJECT_DIR}/main.py

# Restart policy: always restart on crash, wait 5s between attempts
Restart=on-failure
RestartSec=5s
# Limit restart attempts (prevent crash-loop hammering)
StartLimitIntervalSec=120
StartLimitBurst=5

# Allow 30s to gracefully shut down before SIGKILL
TimeoutStopSec=30

# Logging — view with: sudo journalctl -u walle-hw -f
StandardOutput=journal
StandardError=journal
SyslogIdentifier=walle-ai

[Install]
WantedBy=multi-user.target
EOF

log "Service file written."

# ── Enable user linger (so user services survive without login) ───────────────
log "Enabling user linger for $CURRENT_USER..."
sudo loginctl enable-linger "$CURRENT_USER" 2>/dev/null || warn "loginctl linger not available (not critical)"

# ── Reload systemd and enable service ────────────────────────────────────────
log "Reloading systemd daemon..."
sudo systemctl daemon-reload

log "Enabling ${SERVICE_NAME} to start on boot..."
sudo systemctl enable "${SERVICE_NAME}.service"

# ── Start the service now ─────────────────────────────────────────────────────
log "Starting ${SERVICE_NAME} now..."
sudo systemctl start "${SERVICE_NAME}.service"
sleep 3

# ── Status check ─────────────────────────────────────────────────────────────
if sudo systemctl is-active "${SERVICE_NAME}.service" &>/dev/null; then
    log "✅ ${SERVICE_NAME} is RUNNING!"
else
    warn "${SERVICE_NAME} failed to start. Checking logs..."
    sudo journalctl -u "${SERVICE_NAME}.service" --no-pager -n 20
fi

# ── Summary ───────────────────────────────────────────────────────────────────
echo ""
log "========================================"
log "✅ WALL-E Boot Service Setup Complete!"
log "========================================"
echo ""
info "WALL-E will now auto-start every time the Pi boots."
echo ""
info "Useful commands:"
info "  View live logs:    sudo journalctl -u walle-hw -f"
info "  Check status:      sudo systemctl status walle-hw"
info "  Restart manually:  sudo systemctl restart walle-hw"
info "  Stop:              sudo systemctl stop walle-hw"
info "  Disable auto-boot: sudo systemctl disable walle-hw"
echo ""
